version: "3"
services:
  develop:
    build: .
    ports:
      - "8080:8080"
    container_name: rw-lp
    environment:
      PORT: 8080
      CT_URL: http://mymachine:9000
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      API_VERSION: v1
      CT_REGISTER_MODE: auto
      LOCAL_URL: http://mymachine:8080
      FASTLY_ENABLED: "false"
    command: start
    restart: always
