version: "3"
services:
  test:
    build: .
    ports:
      - "3000:3000"
    container_name: rw-lp-test
    environment:
      NODE_ENV: test
      CT_URL: http://mymachine:9000
      API_VERSION: v1
      CT_REGISTER_MODE: auto
    command: test
