apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: rw-lp
  name: rw-lp
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: rw-lp
    spec:
      containers:
      - name: rw-lp
        image: vizzuality/rw-lp
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        args:
          - start
        ports:
          - containerPort: 8080

      restartPolicy: Always
