apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: rw-lp
    app: rw
  name: rw-lp
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: rw-lp
    spec:
      containers:
      - name: rw-lp
        image: vizzuality/rw-lp
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
        args:
          - start
        ports:
          - containerPort: 8080

      restartPolicy: Always
