apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: rw-lp
    app: rw
  name: rw-lp
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: rw-lp
    spec:
      containers:
      - name: rw-lp
        image: vizzuality/rw-lp
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.1"
            memory: "128M"
          limits:
            cpu: "0.5"
            memory: "256M"
        args:
          - start
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15

      restartPolicy: Always
