apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rw-lp
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: rw-lp
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
